// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlcsAjoFb4ov9yUVE-QGjqXUvH1xrHh8g',
    appId: '1:828509625969:web:34f1ece5322a572d32c5d0',
    messagingSenderId: '828509625969',
    projectId: 'first-app-5e062',
    authDomain: 'first-app-5e062.firebaseapp.com',
    storageBucket: 'first-app-5e062.firebasestorage.app',
    measurementId: 'G-GS217V1M3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRBKbVri_1mFkWfrgy8L1UJN7vFIWgkUk',
    appId: '1:828509625969:android:87ff5863865064de32c5d0',
    messagingSenderId: '828509625969',
    projectId: 'first-app-5e062',
    storageBucket: 'first-app-5e062.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2000HoZy3mi2f7O6_RrIVGNNI0R6UaRg',
    appId: '1:828509625969:ios:a5841893fb17aa1832c5d0',
    messagingSenderId: '828509625969',
    projectId: 'first-app-5e062',
    storageBucket: 'first-app-5e062.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2000HoZy3mi2f7O6_RrIVGNNI0R6UaRg',
    appId: '1:828509625969:ios:a5841893fb17aa1832c5d0',
    messagingSenderId: '828509625969',
    projectId: 'first-app-5e062',
    storageBucket: 'first-app-5e062.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlcsAjoFb4ov9yUVE-QGjqXUvH1xrHh8g',
    appId: '1:828509625969:web:5053e759950548d832c5d0',
    messagingSenderId: '828509625969',
    projectId: 'first-app-5e062',
    authDomain: 'first-app-5e062.firebaseapp.com',
    storageBucket: 'first-app-5e062.firebasestorage.app',
    measurementId: 'G-7K3SMCPHRM',
  );
}
